# Generated by Django 2.2.8 on 2020-07-06 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('selected', models.BooleanField(blank=True)),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=70)),
                ('contact', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=500)),
                ('message', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=70)),
                ('contact', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=100)),
                ('CV', models.FileField(upload_to='')),
                ('citizenship', models.ImageField(upload_to='media/FinancialForm')),
                ('certificates', models.FileField(upload_to='')),
                ('photo', models.ImageField(upload_to='media/FinancialForm')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('address', models.CharField(default='', max_length=70)),
                ('contact', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=400, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='media')),
                ('fullname', models.CharField(max_length=400)),
                ('contact', models.CharField(max_length=50)),
                ('Bio', models.TextField(blank=True)),
                ('designation', models.CharField(max_length=400)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('facebook_link', models.URLField(blank=True, max_length=500)),
                ('instagram_link', models.URLField(blank=True, max_length=500)),
                ('twitter_link', models.URLField(blank=True, max_length=500)),
                ('website', models.URLField(blank=True, max_length=400)),
                ('linked', models.URLField(blank=True, max_length=400)),
                ('github', models.URLField(blank=True, max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='media')),
                ('date_created', models.DateField()),
                ('date_updated', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SessionCategory')),
            ],
        ),
        migrations.CreateModel(
            name='BlogNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.BlogCategory')),
            ],
        ),
    ]
