# Generated by Django 2.2.8 on 2020-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcard',
            name='Bio',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
