# Generated by Django 2.2.8 on 2020-07-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200708_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcard',
            name='Bio',
            field=models.TextField(max_length=500, unique=True),
        ),
    ]
