# Generated by Django 2.2.8 on 2020-07-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200708_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamcard',
            name='Bio',
            field=models.TextField(max_length=500),
        ),
    ]
