# Generated by Django 2.2.8 on 2020-07-13 07:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200713_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NLE_info', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Our_story', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('Our_mission', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
