# Generated by Django 2.2.8 on 2020-07-13 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200713_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteinfo',
            name='Career_Session',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='Financial_Advisor',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websiteinfo',
            name='Financial_Session',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
