# Generated by Django 3.0.8 on 2020-07-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_productpolicies'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_link', models.URLField(blank=True, max_length=500)),
                ('instagram_link', models.URLField(blank=True, max_length=500)),
                ('twitter_link', models.URLField(blank=True, max_length=500)),
                ('youtube_link', models.URLField(blank=True, max_length=500)),
                ('contact', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SocialSitesInfo',
        ),
    ]
