# Generated by Django 2.2.8 on 2020-08-07 04:22

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_sessioncategory_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteinfo',
            name='Career_Session',
        ),
        migrations.RemoveField(
            model_name='websiteinfo',
            name='Financial_Advisor',
        ),
        migrations.RemoveField(
            model_name='websiteinfo',
            name='Financial_Session',
        ),
        migrations.CreateModel(
            name='TrainingSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/trainingsessionimages/')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.SessionCategory')),
            ],
        ),
    ]
