# Generated by Django 2.2.8 on 2020-08-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200807_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceform',
            name='choices',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
