# Generated by Django 2.2.8 on 2020-08-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200808_0803'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductPolicies',
        ),
        migrations.DeleteModel(
            name='ProductPoliciesDetails',
        ),
    ]
